package gui.swing.zadania;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patryk
 */
public class Zadanie3 extends javax.swing.JFrame {

    private String ostatniaSciezka;

    public Zadanie3() {
        initComponents();
        ostatniaSciezka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        menu = new javax.swing.JMenuBar();
        filesMenu = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        MenuSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        AdresyMenu = new javax.swing.JMenu();
        menuDom = new javax.swing.JMenuItem();
        menuSzkola = new javax.swing.JMenuItem();
        menuFirma = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        menuForeground = new javax.swing.JMenu();
        menuBlue = new javax.swing.JMenuItem();
        menuOrange = new javax.swing.JMenuItem();
        menuRandom = new javax.swing.JMenuItem();
        backgroundMenu = new javax.swing.JMenu();
        menuBlue2 = new javax.swing.JMenuItem();
        menuOrange2 = new javax.swing.JMenuItem();
        menuRandom2 = new javax.swing.JMenuItem();
        fontsMenu = new javax.swing.JMenu();
        menuF8 = new javax.swing.JMenuItem();
        menuF10 = new javax.swing.JMenuItem();
        menuF12 = new javax.swing.JMenuItem();
        menuF14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text.setColumns(20);
        text.setFont(new Font("Monospaced", 0, 12)); // NOI18N
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        filesMenu.setText("File");

        menuOpen.setText("Open");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        filesMenu.add(menuOpen);

        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        filesMenu.add(menuSave);

        MenuSaveAs.setText("Save as...");
        MenuSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSaveAsActionPerformed(evt);
            }
        });
        filesMenu.add(MenuSaveAs);
        filesMenu.add(jSeparator1);

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        filesMenu.add(MenuExit);

        menu.add(filesMenu);

        editMenu.setText("Edit");

        AdresyMenu.setText("Adresy");

        menuDom.setText("Dom");
        AdresyMenu.add(menuDom);

        menuSzkola.setText("Szkola");
        AdresyMenu.add(menuSzkola);

        menuFirma.setText("Firma");
        AdresyMenu.add(menuFirma);

        editMenu.add(AdresyMenu);

        menu.add(editMenu);

        optionsMenu.setText("Options");

        menuForeground.setText("Foreground");

        menuBlue.setText("Blue");
        menuBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlueActionPerformed(evt);
            }
        });
        menuForeground.add(menuBlue);

        menuOrange.setText("Orange");
        menuOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrangeActionPerformed(evt);
            }
        });
        menuForeground.add(menuOrange);

        menuRandom.setText("Random");
        menuRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRandomActionPerformed(evt);
            }
        });
        menuForeground.add(menuRandom);

        optionsMenu.add(menuForeground);

        backgroundMenu.setText("Background");

        menuBlue2.setText("Blue");
        menuBlue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlue2ActionPerformed(evt);
            }
        });
        backgroundMenu.add(menuBlue2);

        menuOrange2.setText("Orange");
        menuOrange2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrange2ActionPerformed(evt);
            }
        });
        backgroundMenu.add(menuOrange2);

        menuRandom2.setText("Random");
        menuRandom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRandom2ActionPerformed(evt);
            }
        });
        backgroundMenu.add(menuRandom2);

        optionsMenu.add(backgroundMenu);

        fontsMenu.setText("Font size");

        menuF8.setText("8");
        menuF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuF8ActionPerformed(evt);
            }
        });
        fontsMenu.add(menuF8);

        menuF10.setText("10");
        menuF10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuF10ActionPerformed(evt);
            }
        });
        fontsMenu.add(menuF10);

        menuF12.setText("12");
        menuF12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuF12ActionPerformed(evt);
            }
        });
        fontsMenu.add(menuF12);

        menuF14.setText("14");
        menuF14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuF14ActionPerformed(evt);
            }
        });
        fontsMenu.add(menuF14);

        optionsMenu.add(fontsMenu);

        menu.add(optionsMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        save();
    }//GEN-LAST:event_menuSaveActionPerformed

    private void MenuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSaveAsActionPerformed
        saveAs();

    }//GEN-LAST:event_MenuSaveAsActionPerformed

   


    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        String pelnaSciezka = askForPath(FileDialog.LOAD);
        ostatniaSciezka = pelnaSciezka;
        loadFile(pelnaSciezka);
    }//GEN-LAST:event_menuOpenActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        int odpowiedz = JOptionPane.showConfirmDialog(this, "Czy na pewno chcesz zamknąć program?", "Okno zamknięcia", 1);
        if (odpowiedz == JOptionPane.OK_OPTION) {
            save();
            System.exit(0);
        }
    }//GEN-LAST:event_MenuExitActionPerformed

    private void menuBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlueActionPerformed
        changeForeground(Color.BLUE);
    }//GEN-LAST:event_menuBlueActionPerformed

    private void menuOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrangeActionPerformed
        changeForeground(Color.ORANGE);
    }//GEN-LAST:event_menuOrangeActionPerformed

    private void menuRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRandomActionPerformed
        changeForeground(getRandomColor());
    }//GEN-LAST:event_menuRandomActionPerformed

    private void menuBlue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlue2ActionPerformed
        changeBackground(Color.BLUE);
    }//GEN-LAST:event_menuBlue2ActionPerformed

    private void menuOrange2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrange2ActionPerformed
        changeBackground(Color.ORANGE);
    }//GEN-LAST:event_menuOrange2ActionPerformed

    private void menuRandom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRandom2ActionPerformed
        changeBackground(getRandomColor());
    }//GEN-LAST:event_menuRandom2ActionPerformed

    private void menuF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuF8ActionPerformed
        changeFontSize(8);
    }//GEN-LAST:event_menuF8ActionPerformed

    private void menuF10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuF10ActionPerformed
        changeFontSize(10);
    }//GEN-LAST:event_menuF10ActionPerformed

    private void menuF12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuF12ActionPerformed
        changeFontSize(12);
    }//GEN-LAST:event_menuF12ActionPerformed

    private void menuF14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuF14ActionPerformed
        changeFontSize(14);
    }//GEN-LAST:event_menuF14ActionPerformed

    
     private void save() {
        if (ostatniaSciezka.isEmpty()) {
            saveAs();
        } else {
            saveFile(ostatniaSciezka);
        }
    }
    
      private void saveAs() {
        String pelnaSciezka = askForPath(FileDialog.SAVE);
        ostatniaSciezka = pelnaSciezka;
        saveFile(pelnaSciezka);
    }
      
          private void loadFile(String pelnaSciezka) {
        try {

            File file = new File(pelnaSciezka);

            Scanner scanner = new Scanner(file);
            String loadedText = "";
            while (scanner.hasNextLine()) {
                loadedText += scanner.nextLine() + "\n";
            }
            text.setText(loadedText);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Problem z odczytaniem pliku", "Problem odczytu", 0);
        }

    }
          
           private String askForPath(int purpose) {
        FileDialog okno;
        if (purpose == FileDialog.SAVE) {
            okno = new FileDialog(this, "Zapis", FileDialog.SAVE);
        } else {
            okno = new FileDialog(this, "Odczyt", FileDialog.LOAD);
        }
        okno.setVisible(true);
        String pelnaSciezka = "";
        if (okno.getFile() != null) {
            String sciezkaPliku = okno.getDirectory();
            String nazwaPliku = okno.getFile();
            pelnaSciezka = sciezkaPliku + nazwaPliku;
        }
        return pelnaSciezka;
    }

    private void saveFile(String pelnaSciezka) {
        try {
            FileWriter writer = new FileWriter(pelnaSciezka + ".txt");
            writer.write(text.getText());
            writer.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Problem z zapisaniem pliku", "Problem zapisu", 0);
        }
    }
     
     private void changeForeground(Color color) {
        text.setForeground(color);
    }
     
     private void changeBackground(Color color){
         text.setBackground(color);
     }
    
    private Color getRandomColor() {
        Random random = new Random();
        return new Color(
                random.nextInt(256),
                random.nextInt(256),
                random.nextInt(256));
    }

    
    private void changeFontSize(int toSize){
      String actualFont =  text.getFont().getFontName();
      text.setFont(new Font(actualFont, 0, toSize));
    }
    

   

   

   


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadanie3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadanie3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadanie3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadanie3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadanie3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdresyMenu;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuSaveAs;
    private javax.swing.JMenu backgroundMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu filesMenu;
    private javax.swing.JMenu fontsMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuBlue;
    private javax.swing.JMenuItem menuBlue2;
    private javax.swing.JMenuItem menuDom;
    private javax.swing.JMenuItem menuF10;
    private javax.swing.JMenuItem menuF12;
    private javax.swing.JMenuItem menuF14;
    private javax.swing.JMenuItem menuF8;
    private javax.swing.JMenuItem menuFirma;
    private javax.swing.JMenu menuForeground;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuOrange;
    private javax.swing.JMenuItem menuOrange2;
    private javax.swing.JMenuItem menuRandom;
    private javax.swing.JMenuItem menuRandom2;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSzkola;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
