package gui.swing.practise.from_netbeans;

import javax.swing.*;
import java.awt.*;
import java.util.Random;

import static java.awt.Font.ITALIC;

public class Grafika extends javax.swing.JFrame {

    /**
     * Creates new form Grafika
     */
    public Grafika() {
        initComponents();
        setSize(500, 500);
        Figury figury = new Figury();
        add(figury);
        figury.setBounds(0, 0, getWidth(), getHeight());
        setBackground(Color.WHITE);

        Figury figury2 = new Figury();
        add(figury2);
        figury2.setBounds(getWidth(), 0, getWidth(), getHeight());


    }

    class Figury extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            Font font = new Font("SanSerif", ITALIC, 16);
            g.setFont(font);

            g.clearRect(0, 0, getWidth(), getHeight());

            g.setColor(Color.RED);
            g.drawLine(0, getHeight() / 2, getWidth(), getHeight() / 2);
            g.setColor(Color.MAGENTA);
            g.drawRect(30, 70, 80, 90);
            g.drawString("Prostokąt", 30, 200);
            g.drawRect(30, 70 + getHeight() / 2, 80, 90);

            g.setColor(Color.RED);
            g.drawOval(getWidth() / 2 - 40, 70, 80, 90);
            g.drawOval(getWidth() / 2 - 40, 70 + getHeight() / 2, 80, 90);

            Color mojKolor = new Color(36, 36, 255);
            g.setColor(mojKolor);

            g.drawArc(getWidth() / 2 - 40, 70, 80, 90, 45, 85);
            g.fillArc(getWidth() / 2 - 40, 70 + getHeight() / 2, 80, 90, 45, 85);

            Random random = new Random();

            Color losowyKolor =
                    new Color(random.nextInt(255), random.nextInt(255), random.nextInt(255));
            g.setColor(losowyKolor);

            Polygon osmiokat = new Polygon();
            double alfa = 2 * Math.PI / 8;
            int x0 = getWidth() - 100;
            int y0 = 120;

            for (int i = 0; i < 8; i++) {
                osmiokat.addPoint(x0 + (int) (50 * Math.cos(i * alfa)), y0 + (int) (50 * Math.sin(i * alfa)));
            }
            g.drawPolygon(osmiokat);
            osmiokat.translate(0, getHeight() / 2);
            g.fillPolygon(osmiokat);

            int[] x = {0, getWidth() / 2, getWidth()};
            int[] y = {0, 60, 0};
            Color k3 = new Color(100, 240, 50);
            g.setColor(k3);
            g.fillPolygon(x, y, 3);
            g.setColor(Color.black);
            g.drawPolygon(x, y, 3);

            String tytul = "Rysowanie figur geometrycznych";
            int pozycja = getWidth() / 2 - g.getFontMetrics().stringWidth(tytul) / 2;
            g.drawString(tytul, pozycja, 20);


        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafika");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 276, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafika().setVisible(true);
            }
        });
    }
}
