/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.swing.practise.from_netbeans;

import java.awt.Color;
import static java.awt.Color.BLUE;
import static java.awt.Color.RED;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author Daniel
 */
public class Mysz extends javax.swing.JFrame {

    private Color kolorTla;
    private PanelGraficzny panel;
    private int x, y;
    private boolean prawy, lewy, srodkowy;
    private Random random;

    /**
     * Creates new form Mysz
     */
    public Mysz() {
        initComponents();
        kolorTla = Color.BLACK;
        random = new Random();

        setSize(500, 500);
        panel = new PanelGraficzny();
        panel.setBounds(0, 0, getWidth(), getHeight());
        add(panel);

    }

    class PanelGraficzny extends JPanel implements MouseListener {

        public PanelGraficzny() {
            addMouseListener(this);
        }

        @Override
        public void paintComponent(Graphics g) {
            g.setColor(kolorTla);
            g.fillRect(0, 0, getWidth(), getHeight());
            if (lewy) {
                g.setColor(RED);
                g.fillOval(x, y, 80, 80);
            } else if (srodkowy) {
                g.setColor(Color.GREEN);
                g.fillRect(x, y, 80, 80);
            } else {
                g.setColor(BLUE);
                g.drawArc(x, y, 80, 80, 40, 45);
            }

        }

        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mousePressed(MouseEvent e) {
            x = e.getX();
            y = e.getY();
            lewy = e.getButton() == MouseEvent.BUTTON1;
            srodkowy = e.getButton() == MouseEvent.BUTTON2;
            prawy = e.getButton() == MouseEvent.BUTTON3;

            if (e.isControlDown()) {
                kolorTla = new Color(
                        random.nextInt(255),
                        random.nextInt(255),
                        random.nextInt(255)
                );

            }
            repaint();

        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafika z wykorzystaniem myszy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mysz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mysz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mysz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mysz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mysz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    // End of variables declaration
}
