package gui.swing.practise.from_netbeans;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel
 */

public class OknoForm extends javax.swing.JFrame {

    private double liczba1, liczba2, wynik;

    public OknoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        poleLiczby1 = new javax.swing.JTextField();
        poleLiczby2 = new javax.swing.JTextField();
        poleWyniku = new javax.swing.JTextField();
        wyborOperacji = new javax.swing.JComboBox<>();
        przyciskOblicz = new javax.swing.JButton();
        PrzyciskDopisz = new javax.swing.JButton();
        PrzyciskKasuj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObszarWyswietlania = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dzialania arytmetyczne");

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("pierwszy argument");

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("drugi argument");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("wynik obliczeń");

        poleLiczby1.setBackground(new java.awt.Color(0, 204, 204));
        poleLiczby1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                poleLiczby1KeyTyped(evt);
            }
        });

        poleLiczby2.setBackground(new java.awt.Color(0, 204, 204));
        poleLiczby2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                poleLiczby2KeyTyped(evt);
            }
        });

        poleWyniku.setEditable(false);
        poleWyniku.setBackground(new java.awt.Color(51, 153, 255));

        wyborOperacji.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        wyborOperacji.setToolTipText("Wybierz działanie");
        wyborOperacji.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                wyborOperacjiItemStateChanged(evt);
            }
        });
        wyborOperacji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborOperacjiActionPerformed(evt);
            }
        });

        przyciskOblicz.setText("Oblicz");
        przyciskOblicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskObliczActionPerformed(evt);
            }
        });

        PrzyciskDopisz.setText("Dopisz");
        PrzyciskDopisz.setEnabled(false);
        PrzyciskDopisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrzyciskDopiszActionPerformed(evt);
            }
        });

        PrzyciskKasuj.setText("Kasuj");
        PrzyciskKasuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrzyciskKasujActionPerformed(evt);
            }
        });

        ObszarWyswietlania.setEditable(false);
        ObszarWyswietlania.setColumns(20);
        ObszarWyswietlania.setRows(3);
        ObszarWyswietlania.setTabSize(6);
        jScrollPane1.setViewportView(ObszarWyswietlania);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(przyciskOblicz)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(poleLiczby2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                                        .addComponent(poleLiczby1)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(poleWyniku, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(PrzyciskDopisz)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(PrzyciskKasuj, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(wyborOperacji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(poleLiczby1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(poleLiczby2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(wyborOperacji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(przyciskOblicz, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(poleWyniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PrzyciskDopisz)
                                        .addComponent(PrzyciskKasuj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>

    private void przyciskObliczActionPerformed(java.awt.event.ActionEvent evt) {
        PrzyciskDopisz.setEnabled(false);

        String danePolaLiczby1 = poleLiczby1.getText();
        String danePolaLiczby2 = poleLiczby2.getText();
        try {
            liczba1 = Double.parseDouble(danePolaLiczby1.replace(",", "."));
            liczba2 = Double.parseDouble(danePolaLiczby2.replace(",", "."));
            switch((String)wyborOperacji.getSelectedItem()){
                case "+":
                    wynik = liczba1 + liczba2;
                    break;
                case "-":
                    wynik = liczba1 - liczba2;
                    break;
                case "*":
                    wynik = liczba1 * liczba2;
                    break;
                case "/":
                    if(liczba2 == 0){
                        throw new ArithmeticException("Dzielenie przez zero, co to ma być!");
                    }
                    wynik = liczba1 / liczba2;
                    break;
                default:
                    System.err.println("Błąd wyboru operacji");
            }

            NumberFormat format = new DecimalFormat("0.###");
            poleWyniku.setText(format.format(wynik));
            PrzyciskDopisz.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Błędnie podano wartość liczbową argumentu", "Niepoprawne dane",0);
        }catch(ArithmeticException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Niepoprawne dane",0);
        }


    }

    private void poleLiczby1KeyTyped(java.awt.event.KeyEvent evt) {
        poleWyniku.setText("");
        PrzyciskDopisz.setEnabled(false);
    }

    private void poleLiczby2KeyTyped(java.awt.event.KeyEvent evt) {
        poleWyniku.setText("");
        PrzyciskDopisz.setEnabled(false);
    }

    private void wyborOperacjiItemStateChanged(java.awt.event.ItemEvent evt) {
        poleWyniku.setText("");
        PrzyciskDopisz.setEnabled(false);
    }

    private void PrzyciskDopiszActionPerformed(java.awt.event.ActionEvent evt) {
        String operacja = liczba1 + (String) wyborOperacji.getSelectedItem()
                + liczba2 + "="+poleWyniku.getText() + "\n";
        ObszarWyswietlania.append(operacja);
    }

    private void PrzyciskKasujActionPerformed(java.awt.event.ActionEvent evt) {
        int odpowiedz= JOptionPane.showConfirmDialog(this, "Czy na pewno chcesz skasować przeszłe operacje?","Pytanie",2);
        if(odpowiedz == JOptionPane.YES_OPTION){
            ObszarWyswietlania.setText("");
        }

    }

    private void wyborOperacjiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea ObszarWyswietlania;
    private javax.swing.JButton PrzyciskDopisz;
    private javax.swing.JButton PrzyciskKasuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField poleLiczby1;
    private javax.swing.JTextField poleLiczby2;
    private javax.swing.JTextField poleWyniku;
    private javax.swing.JButton przyciskOblicz;
    private javax.swing.JComboBox<String> wyborOperacji;
    // End of variables declaration
}
