package gui.swing.practise.from_netbeans;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.WHITE;
import static java.awt.Color.YELLOW;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Daniel
 */
public class Skoczek extends javax.swing.JFrame {

    private PanelGraficzny panel;

    /**
     * Creates new form Skoczek
     */
    public Skoczek() {
        initComponents();
        setSize(500, 500);
        setBackground(WHITE);
        panel = new PanelGraficzny();
        add(panel);
        panel.setBounds(0, 0, getWidth(), getHeight());

    }

    class PanelGraficzny extends JPanel implements ActionListener, MouseListener {

        private Color kolor;
        private int x, y;
        private Random random;
        private Timer timer;

        public PanelGraficzny() {
            kolor = YELLOW;
            random = new Random();
            timer = new Timer(500,this);
            addMouseListener(this);

            timer.start();
        }

        @Override
        protected void paintComponent(Graphics g) {
            g.clearRect(0, 0, getWidth(), getHeight());
            g.translate(x, y);
            g.setColor(kolor);
            g.fillOval(0, 0, 50, 50);
            g.setColor(BLACK);
            g.fillOval(10, 15, 6, 6);
            g.fillOval(35, 15, 6, 6);
            g.drawArc(10, 10, 30, 30, -100, 80);

        }

        @Override
        public void actionPerformed(ActionEvent arg0) {
            x = random.nextInt(getWidth() - 60);
            y = random.nextInt(getHeight() - 80);

            kolor = new Color(
                    random.nextInt(255),
                    random.nextInt(255),
                    random.nextInt(255)
            );

            repaint();
        }

        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mousePressed(MouseEvent e) {
            if(e.getButton()== MouseEvent.BUTTON1){
                timer.start();
            }else if (e.getButton() == MouseEvent.BUTTON3){
                timer.stop();
            }

        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skoczek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skoczek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skoczek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skoczek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Skoczek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    // End of variables declaration
}
